// 为了保证视频页面的不可改变统一设定第一个为中心区域

const layout = {
  1: {
    name: "默认布局1",
    value: 1,
    icon: new URL(
      "@/assets/images/templates/electronicSealTemplate1.png",
      import.meta.url
    ).href,
    data: [
      {
        value: 1, //插槽值
        grid: "1/ 1 / 3 / 4", //布局位置
        component: "charts1", //表单名称
        note: "中心区域", //备注
        size: "large", //大小
        disabled: true, //是否禁用
        tip: "中心区域不可编辑", //提示信息
        img: undefined,
      },
      {
        value: 2,
        grid: "1/4/2/5",
        component: undefined,
        note: "右1",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 3,
        grid: "2/4/3/5",
        component: undefined,
        note: "右2",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 4,
        grid: "3/4/4/5",
        component: undefined,
        note: "右3",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 5,
        grid: "3/1/4/2",
        component: undefined,
        note: "下1",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 6,
        grid: "3/2/4/3",
        component: undefined,
        note: "下2",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 7,
        grid: "3/3/4/4",
        component: undefined,
        note: "下3",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
    ],
  },

  2: {
    name: "默认布局2",
    value: 2,
    icon: new URL(
      "@/assets/images/templates/electronicSealTemplate2.png",
      import.meta.url
    ).href,
    data: [
      {
        value: 1,
        grid: "1/ 2 / 3 / 4",
        component: "charts1",
        note: "中心区域",
        size: "large",
        disabled: true,
        tip: "中心区域不可编辑",
        img: undefined,
      },
      {
        value: 2,
        grid: "1/1/4/2",
        component: undefined,
        note: "左侧区域",
        size: "small",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 3,
        grid: "1/4/2/5",
        component: undefined,
        note: "右1",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 4,
        grid: "3/4/4/5",
        component: undefined,
        note: "右2",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 5,
        grid: "2/4/3/5",
        component: undefined,
        note: "右3",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 6,
        grid: "3/2/4/3",
        component: undefined,
        note: "下1",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 7,
        grid: "3/3/4/4",
        component: undefined,
        note: "下2",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
    ],
  },

  3: {
    name: "默认布局3",
    value: 3,
    icon: new URL(
      "@/assets/images/templates/electronicSealTemplate3.png",
      import.meta.url
    ).href,
    data: [
      {
        value: 1,
        grid: "1/ 2 / 3 / 4",
        component: "charts1",
        note: "中心区域",
        size: "large",
        disabled: true,
        tip: "中心区域不可编辑",
        img: undefined,
      },
      {
        value: 2,
        grid: "1/1/2/2",
        component: undefined,
        note: "左1",
        size: "small",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 3,
        grid: "2/1/3/2",
        component: undefined,
        note: "左2",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 4,
        grid: "3/1/4/2",
        component: undefined,
        note: "左3",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 5,
        grid: "1/4/4/5",
        component: undefined,
        note: "右侧区域",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 6,
        grid: "3/2/4/3",
        component: undefined,
        note: "下1",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 7,
        grid: "3/3/4/4",
        component: undefined,
        note: "下2",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
    ],
  },

  4: {
    name: "默认布局4",
    value: 4,
    icon: new URL(
      "@/assets/images/templates/electronicSealTemplate4.png",
      import.meta.url
    ).href,
    data: [
      {
        value: 1,
        grid: "1/ 2 / 4 / 4",
        component: "charts1",
        note: "中心区域",
        size: "large",
        disabled: true,
        tip: "中心区域不可编辑",
        img: undefined,
      },
      {
        value: 2,
        grid: "1/1/2/2",
        component: undefined,
        note: "左1",
        size: "small",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 3,
        grid: "2/1/3/2",
        component: undefined,
        note: "左2",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 4,
        grid: "3/1/4/2",
        component: undefined,
        note: "左3",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 5,
        grid: "1/4/2/5",
        component: undefined,
        note: "右1",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 6,
        grid: "2/4/3/5",
        component: undefined,
        note: "右2",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 7,
        grid: "3/4/4/5",
        component: undefined,
        note: "右3",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
    ],
  },

  5: {
    name: "默认布局5",
    value: 5,
    icon: new URL(
      "@/assets/images/templates/electronicSealTemplate5.png",
      import.meta.url
    ).href,
    data: [
      {
        value: 1,
        grid: "1/ 2 / 3 / 4",
        component: "charts1",
        note: "中心区域",
        size: "large",
        disabled: true,
        tip: "中心区域不可编辑",
        img: undefined,
      },
      {
        value: 2,
        grid: "1/1/2/2",
        component: undefined,
        note: "左1",
        size: "small",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 3,
        grid: "2/1/3/2",
        component: undefined,
        note: "左2",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 4,
        grid: "3/1/4/2",
        component: undefined,
        note: "左3",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 5,
        grid: "1/4/2/5",
        component: undefined,
        note: "右1",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 6,
        grid: "2/4/3/5",
        component: undefined,
        note: "右2",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 7,
        grid: "3/4/4/5",
        component: undefined,
        note: "右3",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 8,
        grid: "3/2/4/3",
        component: undefined,
        note: "下1",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 9,
        grid: "3/3/4/4",
        component: undefined,
        note: "下2",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
    ],
  },

  6: {
    name: "默认布局6",
    value: 6,
    icon: new URL(
      "@/assets/images/templates/electronicSealTemplate6.png",
      import.meta.url
    ).href,
    data: [
      {
        value: 1, //插槽值
        grid: "1/ 1 / 3 / 4", //布局位置
        component: "charts1", //表单名称
        note: "中心区域", //备注
        size: "large", //大小
        disabled: true, //是否禁用
        tip: "中心区域不可编辑", //提示信息
        img: undefined,
      },
      {
        value: 2,
        grid: "1/4/4/5",
        component: undefined,
        note: "右1",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 4,
        grid: "3/1/4/2",
        component: undefined,
        note: "下1",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 5,
        grid: "3/2/4/3",
        component: undefined,
        note: "下2",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
      {
        value: 6,
        grid: "3/3/4/4",
        component: undefined,
        note: "下3",
        size: "mini",
        disabled: false,
        tip: "可替换模块",
        img: undefined,
      },
    ],
  },
};

export default layout;
